---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: alb-controller-schedule
  namespace: kube-system
spec:
  scaleTargetRef:
    name: aws-load-balancer-controller
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "2"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-secrets-schedule
  namespace: external-secrets
spec:
  scaleTargetRef:
    name: external-secrets
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-secrets-cert-controller-schedule
  namespace: external-secrets
spec:
  scaleTargetRef:
    name: external-secrets-cert-controller
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-secrets-webhook-schedule
  namespace: external-secrets
spec:
  scaleTargetRef:
    name: external-secrets-webhook
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: external-dns-schedule
  namespace: external-dns
spec:
  scaleTargetRef:
    name: external-dns
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
