resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

metricServer:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

crds:
  install: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

replicaCount: 1

serviceAccount:
  create: true
