apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debian12-mirror-pvc
  namespace: mirrors
  annotations:
    efs.csi.aws.com/volume-id: fs-0b0491ead2bac1c8c
spec:
  accessModes:
    - ReadWriteMany

  storageClassName: efs-mirror-sc

  volumeName: debian12-mirror-efs

  resources:
    requests:
      storage: 100Gi
