apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debian12-mirror-pvc
  namespace: mirrors
spec:
  accessModes:
    - ReadWriteMany

  storageClassName: efs-mirror-sc

  resources:
    requests:
      storage: 100Gi
