apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian12-mirror-sync
  namespace: mirrors
  labels:
    app: debian12-mirror-sync
spec:
  replicas: 1

  selector:
    matchLabels:
      app: debian12-mirror-sync

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: debian12-mirror-sync
      annotations:
        mirror.azubisuccess.space/sync-at: "never"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: debian12-sync
          image: wazaglo/debian12-mirror@sha256:c512bae3d99d92453bb99034c4436bbd6e0c6699176fb530862cf33dea9632a1
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 0
            runAsNonRoot: false

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi

          volumeMounts:
            - name: mirror-data
              mountPath: /var/spool/apt-mirror
            - name: sync-conf
              mountPath: /conf
              readOnly: true
      volumes:
        - name: mirror-data
          persistentVolumeClaim:
            claimName: debian12-mirror-pvc
        - name: sync-conf
          configMap:
            name: debian12-sync-conf
            defaultMode: 0555
