apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-mirror-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b0491ead2bac1c8c
  provisioningParameters.accessPointId: "fsap-020b79f4588c2d482"
  directoryPerms: "755"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/dynamic_provisioning"
mountOptions:
  - tls
reclaimPolicy: Retain
volumeBindingMode: Immediate
