apiVersion: v1
kind: Pod
metadata:
  name: efs-test
  namespace: mirrors

spec:

  containers:

  - name: test
    image: alpine

    command:
      - sh
      - -c
      - |
        echo "EFS TEST $(date)" > /data/test.txt
        sleep 3600

    volumeMounts:

    - name: efs-volume
      mountPath: /data


  volumes:

  - name: efs-volume

    persistentVolumeClaim:
      claimName: debian12-mirror-pvc
