apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - debian12-mirror-pvc.yaml

  - configmap-debian12-sync.yaml
  - deployment-debian12-sync.yaml
  - cronjob-debian12-sync-trigger.yaml

  - configmap-snapshot.yaml
  - cronjob-debian12-snapshot.yaml

  - configmap-mirror-nginx.yaml
  - deployment-mirror-nginx.yaml
  - service.yaml
