apiVersion: v1
kind: Service
metadata:
  name: debian12-mirror-service
  namespace: mirrors
  labels:
    app: debian12-mirror-nginx
spec:
  type: ClusterIP
  selector:
    app: debian12-mirror-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
