apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yml
  - scaledobjects.yaml

configMapGenerator:
  - name: nginx-sites
    files:
      - sites/_default.conf
      - sites/grafana.azubisuccess.space.conf
      - sites/debian-mirror.azubisuccess.space.conf

patches:
  - target:
      kind: ConfigMap
      name: nginx-sites
    patch: |-
      - op: add
        path: /metadata/namespace
        value: nginx-demo
