apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          valid_status_codes: [200, 301, 302]
          follow_redirects: true
          preferred_ip_protocol: ip4
