apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: /eks-gitops/monitoring/grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: /eks-gitops/monitoring/grafana-admin-password
