apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::195675606509:role/loki-storage-role
automountServiceAccountToken: true
