apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: grafana-efs
  resources:
    requests:
      storage: 5Gi
