apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: grafana-schedule
  namespace: monitoring
spec:
  scaleTargetRef:
    name: grafana
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-schedule
  namespace: monitoring
spec:
  scaleTargetRef:
    name: prometheus
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: loki-schedule
  namespace: monitoring
spec:
  scaleTargetRef:
    name: loki
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: blackbox-schedule
  namespace: monitoring
spec:
  scaleTargetRef:
    name: blackbox
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 60
  cooldownPeriod: 30
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "5 10 * * *"
        end: "54 17 * * *"
        desiredReplicas: "1"
