apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Dev environment root — this is what CI deploys to eks-lab on every merge.
resources:
  - ../../apps/nginx/overlays/dev
  - ../../apps/monitoring/overlays/dev
  - ../../apps/alb
  - ../../apps/mirror
